### ISSUE TITLE
0.6.33 C backend: struct return typed as int64_t — PreparedDmlPlan field access fails

### ISSUE THREAD

**Issue by loreste** [loreste/mako#59]
## Summary

Mako 0.6.33 C backend emits struct-returning functions with `int64_t` return type instead of the actual struct type. Accessing fields on the return value then fails with:

```
error: member reference base type 'int64_t' (aka 'long') is not a structure or union
```

This worked in 0.6.32.

## Reproduction

```mako
struct PreparedDmlPlan {
    kind: string
    error: string
    table: string
    set_col: string
    set_val: string
    where_col: string
    permission: string
    audit_event: string
}

fn make_plan() -> PreparedDmlPlan {
    return PreparedDmlPlan { kind: "update", error: "", table: "t", set_col: "c", set_val: "v", where_col: "w", permission: "update", audit_event: "dml" }
}

fn main() {
    let plan = make_plan()
    if str_eq(plan.error, "") {  // ERROR: member reference base type 'int64_t'
        print("ok")
    }
}
```

Build with: `mako build file.mko --backend c`

## Errors from FayDB build

```
lib.mko:1182:25: error: member reference base type 'int64_t' (aka 'long') is not a structure or union
lib.mko:1190:25: error: member reference base type 'int64_t' (aka 'long') is not a structure or union
lib.mko:1204:5: error: use of undeclared identifier 'PreparedDmlPlan'
```

20 errors total, all related to struct returns being typed as int64_t.

## Environment

- Mako 0.6.33 (`makori0.6.33 darwin/arm64`)
- `--backend c`, both native and cross-compile (`--target x86_64-unknown-linux-gnu`)
- FayDB codebase (~42k lines across 4 .mko files)

## Impact

FayDB cannot build with Mako 0.6.33. Blocked on 0.6.32 binaries.

**Comment by loreste** [comment]
Fixed in d265d82. DCE was incorrectly removing struct definitions (PreparedDmlPlan and 7 others in FayDB). The Expr::Ident change for iterator combinator DCE was adding all local variable names to reachable_fns, which broke the struct retention prefix matching. Fix: only push ident function refs from method call args (map/filter/reduce), not all bare idents. FayDB builds and runs correctly with mako 0.6.33.
